name: coffeecraft
description: Coffeecraft client
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  polymer: ">=0.15.2 <0.17.0"
  core_elements: ">=0.5.0 <0.7.0"
  paper_elements: ">=0.6.0 <0.7.0"
  dartson: ">=0.2.0 <0.3.0"
  option: "^1.1.0"
transformers:
- polymer:
    entry_points:
    - web/index.html
- dartson