name: coffeecraft
description: Coffeecraft client
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  polymer: '>=0.15.1 <0.16.0'
  option: "^1.1.0"
  dartson: ">=0.2.0 <0.3.0"
transformers:
- polymer:
    entry_points:
    - web/index.html
- dartson